modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="lemons4me" #mandatory

version="${file.jarVersion}" #mandatory

displayName="The Lemons 4 Me" #mandatory

credits="Thanks for this mod goes to my friend Jacob" #optional

authors="TheMusicMan28" #optional

description='''
LEMONS!!!!!!!! LEMON BLOCKS, LEMON SWORDS, LEMON ARMOR!!!! EVERYTHING IS LEMONS
'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[31,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
